wandb_version: 1

data_source:
  desc: null
  value: 29var
batch_size:
  desc: null
  value: 20
device:
  desc: null
  value: cuda
epochs:
  desc: null
  value: 500
latent_dim:
  desc: null
  value: 80
lr:
  desc: null
  value: 0.001
break_data:
  desc: null
  value: false
break_size:
  desc: null
  value: 60
leave_out_problematic_features:
  desc: null
  value: true
cutoff_data:
  desc: null
  value: true
feat_dim:
  desc: null
  value: 24
seq_len:
  desc: null
  value: 120
num_samples:
  desc: null
  value: 180
trend_poly:
  desc: null
  value: 2
custom_seas:
  desc: null
  value:
  - - 4
    - 8
reconstruction_wt:
  desc: null
  value: 3.0
hidden_layer_sizes:
  desc: null
  value:
  - 50
  - 100
  - 200
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.0
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716894326
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.12
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
